Retries now send the file correctly.
Islandora/tuque pull request #153
Opened 2017-02-02 21:58 UTC by adam-vessey

**JIRA Ticket**: [ISLANDORA-1901](https://jira.duraspace.org/browse/ISLANDORA-1901)

# What does this Pull Request do?

Prevent timeouts in the event `PUT` requests fail due to spurious HTTP 409 Conflict errors.

# What's new?

Rewind the file handle when retrying.

# How should this be tested?

Regression testing is about it... Spurious issues are spurious.

I've not yet actually tried, but I believe the timeout behaviour described in the ticket can be forced by making bad requests... which is to say, making a request with old last modified dates, resulting in an _actual_ 409... So this PR would fail faster, avoiding the timeouts at least.

# Additional Notes:
* Does this change require documentation to be updated?  No.
* Does this change add any new dependencies?  No.
* Does this change require any other modifications to be made to the repository (ie. Regeneration activity, etc.)? No.
* Could this change impact execution of existing code? No.

# Interested parties

Maintainers: @DiegoPino and @willtp87

2017-02-03 12:13 UTC, willtp87 commented
@adam-vessey did you miss a commit?

2017-02-03 12:44 UTC, jonathangreen commented on HttpConnection.php
> +      $results = $this->doCurlRequest(NULL, $fh);
In the case that the type of the put request is 'none', $fh isn't defined here.

2017-02-03 13:23 UTC, DiegoPino commented on HttpConnection.php
> +      $results = $this->doCurlRequest(NULL, $fh);
@jonathangreen @adam-vessey the absence of $fh seems to be handled by the argument 's [default]( https://github.com/Islandora/tuque/pull/153/commits/213a90bcffa7fc687f8013171110cdc6a2124ecb#diff-2042586689e534b400950d72a360fa29R446)

This seems to consistent with the pre-pull way of doing it for `$file`, but I feel that maybe being explicit on a NULL `$fh` on type `none` would not harm at all.

2017-02-03 13:27 UTC, DiegoPino requested changes
@adam-vessey there is a missing pull for sure regarding tests that is making TRAVIS fail. @willtp87 is that the one you are referring to?

2017-02-07 14:39 UTC, DiegoPino approved these changes

2017-02-07 14:43 UTC, DiegoPino commented
@adam-vessey this looks good. Will wait a few hours in case @jonathangreen has some comments. Will merge after that or today last hour in no comments. Thaks

2017-02-07 15:19 UTC, jonathangreen approved these changes

2017-02-07 15:19 UTC, jonathangreen commented
Looks good to me.

2017-02-07 17:23 UTC, merged

2017-02-07 17:24 UTC, DiegoPino commented
@adam-vessey and @jonathangreen thanks. Merged and JIRA ticket marked as Fixed.